// ============================================================================
// Automatically Generated by SVRF-to-PXL Translator (Prototype)
// ============================================================================
// This file was automatically translated from Calibre SVRF format
// Manual review and validation recommended
// ============================================================================

#include <icv.rh>


// ============================================================================
// LAYER DEFINITIONS
// ============================================================================

DIFF = layer(1, 0);
NWELL = layer(2, 0);
POLY = layer(5, 0);
CONTACT = layer(6, 0);
METAL1 = layer(10, 0);
METAL2 = layer(11, 0);

// ============================================================================
// DRC RULES
// ============================================================================

// Minimum width of diffusion = 0.1um
DIFF_WIDTH_violations = width(DIFF) < 0.1;
drc_deck(DIFF_WIDTH_violations, "DIFF_WIDTH", "Width violation: < 0.1um");

// Minimum spacing between diffusion = 0.14um
DIFF_SPACE_violations = external_distance(DIFF, DIFF) < 0.14;
drc_deck(DIFF_SPACE_violations, "DIFF_SPACE", "Spacing violation: < 0.14um");

// Minimum width of poly = 0.08um
POLY_WIDTH_violations = width(POLY) < 0.08;
drc_deck(POLY_WIDTH_violations, "POLY_WIDTH", "Width violation: < 0.08um");

// Minimum spacing between poly = 0.12um
POLY_SPACE_violations = external_distance(POLY, POLY) < 0.12;
drc_deck(POLY_SPACE_violations, "POLY_SPACE", "Spacing violation: < 0.12um");

GATE = POLY and DIFF;

POLY_NOT_GATE = POLY not GATE;

// Contact width must be 0.06um
CONT_WIDTH_violations = width(CONTACT) < 0.06;
drc_deck(CONT_WIDTH_violations, "CONT_WIDTH", "Width violation: < 0.06um");

// Contact spacing = 0.08um
CONT_SPACE_violations = external_distance(CONTACT, CONTACT) < 0.08;
drc_deck(CONT_SPACE_violations, "CONT_SPACE", "Spacing violation: < 0.08um");

// Diffusion must enclose contact by 0.04um
CONT_DIFF_ENC_violations = external_enclosure(DIFF, CONTACT) < 0.04;
drc_deck(CONT_DIFF_ENC_violations, "CONT_DIFF_ENC", "Enclosure violation: < 0.04um");

// Metal1 minimum width = 0.09um
M1_WIDTH_violations = width(METAL1) < 0.09;
drc_deck(M1_WIDTH_violations, "M1_WIDTH", "Width violation: < 0.09um");

// Metal1 minimum spacing = 0.09um
M1_SPACE_violations = external_distance(METAL1, METAL1) < 0.09;
drc_deck(M1_SPACE_violations, "M1_SPACE", "Spacing violation: < 0.09um");

// Metal1 enclosure of contact = 0.01um
M1_CONT_ENC_violations = external_enclosure(METAL1, CONTACT) < 0.01;
drc_deck(M1_CONT_ENC_violations, "M1_CONT_ENC", "Enclosure violation: < 0.01um");

// Metal2 minimum width = 0.10um
M2_WIDTH_violations = width(METAL2) < 0.1;
drc_deck(M2_WIDTH_violations, "M2_WIDTH", "Width violation: < 0.1um");

// Metal2 minimum spacing = 0.10um
M2_SPACE_violations = external_distance(METAL2, METAL2) < 0.1;
drc_deck(M2_SPACE_violations, "M2_SPACE", "Spacing violation: < 0.1um");

// N-well minimum width = 0.84um
NWELL_WIDTH_violations = width(NWELL) < 0.84;
drc_deck(NWELL_WIDTH_violations, "NWELL_WIDTH", "Width violation: < 0.84um");

// N-well minimum spacing = 1.27um
NWELL_SPACE_violations = external_distance(NWELL, NWELL) < 1.27;
drc_deck(NWELL_SPACE_violations, "NWELL_SPACE", "Spacing violation: < 1.27um");

// ============================================================================
// END OF DRC DECK
// ============================================================================
